name: Databricks DAB CI/CD

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  validate:
    name: Validate DAB Bundle
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: dab_cicd_demo

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Databricks CLI
        uses: databricks/setup-cli@main

      - name: Setup uv
        uses: astral-sh/setup-uv@v6

      - name: Validate Bundle
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: |
          databricks bundle validate -t dev

  deploy:
    name: Deploy DAB to DEV
    needs: validate

    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: dab_cicd_demo

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Databricks CLI
        uses: databricks/setup-cli@main

      - name: Setup uv
        uses: astral-sh/setup-uv@v6

      - name: Deploy Bundle
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: |
          databricks bundle deploy -t dev